### ISSUE TITLE
Using inline vs Twig include

### ISSUE THREAD

**Issue by michalochman** [luwes/craft3-inline#1]
Hi, just wondering if there is any valid reason I'd want to use the inline plugin instead of just regular Twig include tag. Are there any security considerations or something like that? Can you elaborate please?

    {{ inline(assetsUrl ~ '/images/logo.svg') | raw }}

vs

    {% include assetsUrl ~ '/images/logo.svg' %}

**Comment by luwes** [comment]
Hey @michalochman, the `include` tag didn't work in my tests. It's used to include other template parts. This plugin uses the PHP function `file_get_contents`. There are security considerations to be made, you'll have research that a little.

**Comment by michalochman** [comment]
What about using Twig's [`source`](https://twig.symfony.com/doc/2.x/functions/source.html#source) function instead? It should be safer for user supplied SVG files, since it would not render them.

**Comment by luwes** [comment]
@michalochman I haven't tested the source function. Does this work?

**Comment by michalochman** [comment]
@luwes both `{{ source ("icons/icon.svg") }}` and `{% include "icons/icon" %}` work for me. The path is relative to the craft/templates folder. The difference is that the former usage does not parse the file for render, so there is no variable substitution, _etc_.
